config/routes.rb
Rails.application.routes.draw do
  root to: 'view_points#account_dashboard'
  devise_for :users
  ActiveAdmin.routes(self)

  resources :statement_money_lines
  resources :statement_position_nettings
  resources :statement_positions
  resources :statement_deal_leg_fills
  resources :statement_charges
  resources :statement_adjustments
  resources :accounts
  resources :claim_sets
  resources :claims

  get 'view_point/seasonal_spreads' => 'view_points#seasonal_spreads', as: :seasonal_spreads
  get 'view_point/seasonal_spreads_data' => 'view_points#seasonal_spreads_data', as: :seasonal_spreads_data

  get 'view_point/seasonal_spread_sets' => 'view_points#seasonal_spread_sets', as: :seasonal_spread_sets
  get 'view_point/seasonal_spread_sets_data' => 'view_points#seasonal_spread_sets_data', as: :seasonal_spread_sets_data

  get 'view_point/firm_dashboard' => 'view_points#firm_dashboard', as: :firm_dashboard
  get 'view_point/account_dashboard' => 'view_points#account_dashboard', as: :account_dashboard

  get 'view_point/who_what_when' => 'view_points#who_what_when', as: :who_what_when
  post 'view_point/who_what_when_range'  => 'view_points#who_what_when_range',  as: :who_what_when_post
  post 'view_point/firm_what_when_range' => 'view_points#firm_what_when_range', as: :firm_what_when_post
  match 'view_point/firm_what_when' => 'view_points#firm_what_when', as: :firm_what_when, via: [:get, :post]

  #
  get 'view_point/firm_positions_by_claim' => 'view_points#firm_positions_by_claim'
  get 'view_point/firm_statement_positions_by_claim_on' => 'view_points#firm_statement_positions_by_claim_on'
  get 'view_point/firm_statement_money_lines_since' => 'view_points#firm_statement_money_lines_since'

  get 'view_point/positions_by_claim' => 'view_points#positions_by_claim'
  get 'view_point/statement_positions_by_claim_on' => 'view_points#statement_positions_by_claim_on'
  get 'view_point/statement_money_lines_since' => 'view_points#statement_money_lines_since'

  get 'view_point/income_to_expense_ratio_by_claim_set' => 'view_points#income_to_expense_ratio_by_claim_set'
  get 'view_point/income_to_expense_ratio_by_claim_set_for_firm' => 'view_points#income_to_expense_ratio_by_claim_set_for_firm'

  get 'view_point/positions' => 'view_points#positions'

  get 'view_point/statement_money_lines_ytd' => 'view_points#statement_money_lines_ytd', as: :statement_money_lines_ytd

  get 'view_point/positions_by_claim_set' => 'view_points#positions_by_claim_set'
end

app/models/claim_set.rb
# == Schema Information
#
# Table name: claim_sets
#
#  id         :integer          not null, primary key
#  code       :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  sector     :string
#

class ClaimSet < ApplicationRecord
  validates :code, presence: true
  validates :name, presence: true

  has_many :claims
  has_many :chargeables

  scope :spreads, -> {
    joins(:claims => :claim_type).where("claim_types.code = 'SPD'")
  }

  # scope :with_admin, -> {joins(:feed => {:groups => :user}).where('users.admin' => true)}

  def self.select_options_by_code
    select("id, code").order(:code).all.collect {|a| [" #{a.code}", a.id]}
  end

  def self.select_options_by_name
    select("id, name").order(:name).all.collect {|a| [" #{a.name}", a.id]}
  end
end

app/controllers/claim_sets_controller.rb
class ClaimSetsController < ApplicationController
  before_action :set_claim_set, only: [:show, :edit, :update, :destroy]

  # GET /claim_sets
  # GET /claim_sets.json
  def index
    @q = ClaimSet.ransack(params[:q])
    @claim_sets = @q.result.page(params[:page]).per(20)
  end

  # GET /claim_sets/1
  # GET /claim_sets/1.json
  def show
  end

  # GET /claim_sets/new
  def new
    @claim_set = ClaimSet.new
  end

  # GET /claim_sets/1/edit
  def edit
  end

  # POST /claim_sets
  # POST /claim_sets.json
  def create
    @claim_set = ClaimSet.new(claim_set_params)

    respond_to do |format|
      if @claim_set.save
        format.html { redirect_to @claim_set, notice: 'Claim set was successfully created.' }
        format.json { render :show, status: :created, location: @claim_set }
      else
        format.html { render :new }
        format.json { render json: @claim_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claim_sets/1
  # PATCH/PUT /claim_sets/1.json
  def update
    respond_to do |format|
      if @claim_set.update(claim_set_params)
        format.html { redirect_to @claim_set, notice: 'Claim set was successfully updated.' }
        format.json { render :show, status: :ok, location: @claim_set }
      else
        format.html { render :edit }
        format.json { render json: @claim_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claim_sets/1
  # DELETE /claim_sets/1.json
  def destroy
    @claim_set.destroy
    respond_to do |format|
      format.html { redirect_to claim_sets_url, notice: 'Claim set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim_set
      @claim_set = ClaimSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_set_params
      params.require(:claim_set).permit(:code, :name)
    end
end

app/views/claim_sets/_form.html.slim
= form_for @claim_set do |f|
  - if @claim_set.errors.any?
    #error_explanation
      h2 = "#{pluralize(@claim_set.errors.count, "error")} prohibited this claim_set from being saved:"
      ul
        - @claim_set.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/claim_sets/edit.html.slim
h1 Editing claim_set

== render 'form'

= link_to 'Show', @claim_set
'|
= link_to 'Back', claim_sets_path

app/views/claim_sets/index.html.slim
h1 Listing claim_sets

.row
  .large-6.columns
    = paginate @claim_sets
  .large-6.columns
    .btn.btn-default = link_to 'New Claim Set', new_claim_set_path

.row
  .large-12.columns
    table class="table table-striped table-bordered table-condensed table-hover"
      thead
        tr
          th Code
          th Name
          th
          th
          th

      tbody
        - @claim_sets.each do |claim_set|
          tr
            td = claim_set.code
            td = claim_set.name
            td = link_to 'Show', claim_set
            td = link_to 'Edit', edit_claim_set_path(claim_set)
            td = link_to 'Destroy', claim_set, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/claim_sets/new.html.slim
h1 New claim_set

== render 'form'

= link_to 'Back', claim_sets_path

app/views/claim_sets/show.html.slim
p#notice = notice

p
  strong ID:
  = @claim_set.id
p
  strong Code:
  = @claim_set.code
p
  strong Name:
  = @claim_set.name

= link_to 'Edit', edit_claim_set_path(@claim_set)
'|
= link_to 'Back', claim_sets_path