config/routes.rb
Rails.application.routes.draw do
  root to: 'view_points#account_dashboard'
  devise_for :users
  ActiveAdmin.routes(self)

  resources :statement_money_lines
  resources :statement_position_nettings
  resources :statement_positions
  resources :statement_deal_leg_fills
  resources :statement_charges
  resources :statement_adjustments
  resources :accounts
  resources :claim_sets
  resources :claims

  get 'view_point/seasonal_spreads' => 'view_points#seasonal_spreads', as: :seasonal_spreads
  get 'view_point/seasonal_spreads_data' => 'view_points#seasonal_spreads_data', as: :seasonal_spreads_data

  get 'view_point/seasonal_spread_sets' => 'view_points#seasonal_spread_sets', as: :seasonal_spread_sets
  get 'view_point/seasonal_spread_sets_data' => 'view_points#seasonal_spread_sets_data', as: :seasonal_spread_sets_data

  get 'view_point/firm_dashboard' => 'view_points#firm_dashboard', as: :firm_dashboard
  get 'view_point/account_dashboard' => 'view_points#account_dashboard', as: :account_dashboard

  get 'view_point/who_what_when' => 'view_points#who_what_when', as: :who_what_when
  post 'view_point/who_what_when_range'  => 'view_points#who_what_when_range',  as: :who_what_when_post
  post 'view_point/firm_what_when_range' => 'view_points#firm_what_when_range', as: :firm_what_when_post
  match 'view_point/firm_what_when' => 'view_points#firm_what_when', as: :firm_what_when, via: [:get, :post]

  #
  get 'view_point/firm_positions_by_claim' => 'view_points#firm_positions_by_claim'
  get 'view_point/firm_statement_positions_by_claim_on' => 'view_points#firm_statement_positions_by_claim_on'
  get 'view_point/firm_statement_money_lines_since' => 'view_points#firm_statement_money_lines_since'

  get 'view_point/positions_by_claim' => 'view_points#positions_by_claim'
  get 'view_point/statement_positions_by_claim_on' => 'view_points#statement_positions_by_claim_on'
  get 'view_point/statement_money_lines_since' => 'view_points#statement_money_lines_since'

  get 'view_point/income_to_expense_ratio_by_claim_set' => 'view_points#income_to_expense_ratio_by_claim_set'
  get 'view_point/income_to_expense_ratio_by_claim_set_for_firm' => 'view_points#income_to_expense_ratio_by_claim_set_for_firm'

  get 'view_point/positions' => 'view_points#positions'

  get 'view_point/statement_money_lines_ytd' => 'view_points#statement_money_lines_ytd', as: :statement_money_lines_ytd

  get 'view_point/positions_by_claim_set' => 'view_points#positions_by_claim_set'
end

app/models/charge.rb
# == Schema Information
#
# Table name: charges
#
#  id               :integer          not null, primary key
#  account_id       :integer          not null
#  chargeable_id    :integer          not null
#  currency_id      :integer          not null
#  segregation_id   :integer          not null
#  amount           :decimal(, )      not null
#  memo             :string           not null
#  posted_on        :date             not null
#  as_of_on         :date             not null
#  journal_entry_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Charge < ApplicationRecord
  validates :account_id, presence: true
  validates :amount, presence: true
  validates :currency_id, presence: true
  validates :posted_on, presence: true
  validates :as_of_on, presence: true

  belongs_to :account
  belongs_to :currency
  belongs_to :chargeable
  belongs_to :journal_entry
  belongs_to :segregation

  scope :for_account, -> (account_id) { where(account_id: account_id) }
  scope :posted_on, -> (posted_on) { where(posted_on: posted_on) }

  scope :memo_includes, ->(search) {
    current_scope = self
    search.split.uniq.each do |word|
      current_scope = current_scope.where('memo ILIKE ?', "%#{word}%")
    end
    current_scope
  }

  def self.ransackable_scopes(auth_object = nil)
    [:memo_includes]
  end

  def is_clearing?
    chargeable.chargeable_type.code == 'CLR'
  end

  def is_exchange?
    chargeable.chargeable_type.code == 'EXG'
  end

  def is_service?
    chargeable.chargeable_type.code == 'SRV'
  end

  def is_brokerage?
    chargeable.chargeable_type.code == 'BRK'
  end
end

app/controllers/charges_controller.rb
class ChargesController < InheritedResources::Base

  private

    def charge_params
      params.require(:charge).permit(:account_id, :chargeable_id, :currency_id, :segregation_id, :amount, :memo, :posted_on, :as_of_on)
    end
end

app/views/charges/_form.html.slim
= simple_form_for(@charge) do |f|
  = f.error_notification

  .form-inputs
    = f.input :account_id
    = f.input :chargeable_id
    = f.input :currency_id
    = f.input :segregation_id
    = f.input :amount
    = f.input :memo
    = f.input :posted_on
    = f.input :as_of_on

  .form-actions
    = f.button :submit

app/views/charges/edit.html.slim
h1 Editing charge

== render 'form'

= link_to 'Show', @charge
'|
= link_to 'Back', charges_path

app/views/charges/index.html.slim
h1 Listing charges

table
  thead
    tr
      th Account
      th Chargeable
      th Currency
      th Segregation
      th Amount
      th Memo
      th Posted on
      th As of on
      th
      th
      th

  tbody
    - @charges.each do |charge|
      tr
        td = charge.account_id
        td = charge.chargeable_id
        td = charge.currency_id
        td = charge.segregation_id
        td = charge.amount
        td = charge.memo
        td = charge.posted_on
        td = charge.as_of_on
        td = link_to 'Show', charge
        td = link_to 'Edit', edit_charge_path(charge)
        td = link_to 'Destroy', charge, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Charge', new_charge_path

app/views/charges/new.html.slim
h1 New charge

== render 'form'

= link_to 'Back', charges_path

app/views/charges/show.html.slim
p#notice = notice

p
  strong Account:
  = @charge.account_id
p
  strong Chargeable:
  = @charge.chargeable_id
p
  strong Currency:
  = @charge.currency_id
p
  strong Segregation:
  = @charge.segregation_id
p
  strong Amount:
  = @charge.amount
p
  strong Memo:
  = @charge.memo
p
  strong Posted on:
  = @charge.posted_on
p
  strong As of on:
  = @charge.as_of_on

= link_to 'Edit', edit_charge_path(@charge)
'|
= link_to 'Back', charges_path